-- Seed data for i18n schema

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `product_categories`;
TRUNCATE TABLE `product_images`;
TRUNCATE TABLE `product_translations`;
TRUNCATE TABLE `products`;
TRUNCATE TABLE `category_translations`;
TRUNCATE TABLE `categories`;
TRUNCATE TABLE `post_translations`;
TRUNCATE TABLE `posts`;
TRUNCATE TABLE `settings`;
TRUNCATE TABLE `users`;
TRUNCATE TABLE `navigation_items`;
TRUNCATE TABLE `page_translations`;
TRUNCATE TABLE `pages`;
SET FOREIGN_KEY_CHECKS = 1;

-- Categories
INSERT INTO `categories` (`id`, `parent_id`) VALUES (1, NULL), (2, NULL), (3, NULL), (4, NULL), (5, NULL);
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES
(1, 'en', 'Sectional Doors', 'sectional-doors', 'Our sectional doors are engineered for reliability, security, and excellent thermal insulation. Available in a wide range of designs and finishes to perfectly match your home or industrial facility.', 'High-Quality Sectional Doors | Secure & Insulated | DoorHan', 'Discover our premium sectional doors, offering superior insulation, robust security, and modern designs. Perfect for residential garages and industrial applications.'),
(2, 'en', 'Roller Shutter Doors', 'roller-shutter-doors', 'DoorHan roller shutter doors are a compact and durable solution, ideal for applications where space is limited. They provide reliable security for garages, warehouses, and retail storefronts.', 'Durable Roller Shutter Doors | Space-Saving & Secure | DoorHan', 'Explore our space-saving and secure roller shutter doors. Built for durability and performance, they are the ideal choice for commercial and residential properties.'),
(3, 'en', 'High Speed Doors', 'high-speed-doors', 'Increase efficiency and maintain stable climate conditions with our high-speed doors. Designed for intensive use in industrial and commercial environments, they ensure optimized traffic flow and energy savings.', 'High-Speed Industrial Doors | Efficient & Reliable | DoorHan', 'Optimize your operations with DoorHan high-speed doors. Engineered for speed, reliability, and energy efficiency in demanding industrial environments.'),
(4, 'en', 'Folding Doors', 'folding-doors', 'Our industrial folding doors are the perfect solution for very large openings, such as aircraft hangars and large warehouse entrances. They offer robust construction and reliable performance.', 'Industrial Folding Doors for Large Openings | DoorHan', 'Secure and versatile industrial folding doors designed for extra-large openings. Discover our robust and reliable solutions for hangars, shipyards, and industrial facilities.'),
(5, 'en', 'Sliding Gates', 'sliding-gates', 'Automate and secure your property with our range of sliding gates. We offer reliable and aesthetically pleasing solutions for residential, commercial, and industrial applications.', 'Automatic Sliding Gates | Secure & Convenient | DoorHan', 'Enhance your property’s security and convenience with our automatic sliding gates. Durable, reliable, and available in various styles to suit your needs.'),
-- Spanish Translations
(1, 'es', 'Puertas Seccionales', 'puertas-seccionales', 'Nuestras puertas seccionales están diseñadas para ofrecer fiabilidad, seguridad y un excelente aislamiento térmico. Disponibles en una amplia gama de diseños y acabados para adaptarse perfectamente a su hogar o instalación industrial.', 'Puertas Seccionales de Alta Calidad | Seguras y Aislantes | DoorHan', 'Descubra nuestras puertas seccionales de primera calidad, que ofrecen un aislamiento superior, una seguridad robusta y diseños modernos. Perfectas para garajes residenciales e instalaciones industriales.'),
(2, 'es', 'Puertas Enrollables', 'puertas-enrollables', 'Las puertas enrollables de DoorHan son una solución compacta y duradera, ideal para aplicaciones donde el espacio es limitado. Proporcionan seguridad fiable para garajes, almacenes y fachadas de tiendas.', 'Puertas Enrollables Duraderas | Ahorro de Espacio y Seguridad | DoorHan', 'Explore nuestras puertas enrollables seguras y que ahorran espacio. Fabricadas para ofrecer durabilidad y rendimiento, son la opción ideal para propiedades comerciales y residenciales.'),
(3, 'es', 'Puertas Rápidas', 'puertas-rapidas', 'Aumente la eficiencia y mantenga condiciones climáticas estables con nuestras puertas rápidas. Diseñadas para un uso intensivo en entornos industriales y comerciales, garantizan un flujo de tráfico optimizado y un ahorro de energía.', 'Puertas Industriales Rápidas | Eficientes y Fiables | DoorHan', 'Optimice sus operaciones con las puertas rápidas de DoorHan. Diseñadas para ofrecer velocidad, fiabilidad y eficiencia energética en entornos industriales exigentes.'),
(4, 'es', 'Puertas Plegables', 'puertas-plegables', 'Nuestras puertas plegables industriales son la solución perfecta para aberturas muy grandes, como hangares de aviones y grandes entradas de almacenes. Ofrecen una construcción robusta y un rendimiento fiable.', 'Puertas Plegables Industriales para Grandes Aberturas | DoorHan', 'Puertas plegables industriales, seguras y versátiles, diseñadas para aberturas extragrandes. Descubra nuestras soluciones robustas y fiables para hangares, astilleros e instalaciones industriales.'),
(5, 'es', 'Portones Correderos', 'portones-correderos', 'Automatice y asegure su propiedad con nuestra gama de portones correderos. Ofrecemos soluciones fiables y estéticamente agradables para aplicaciones residenciales, comerciales e industriales.', 'Portones Correderos Automáticos | Seguros y Cómodos | DoorHan', 'Mejore la seguridad y comodidad de su propiedad con nuestros portones correderos automáticos. Duraderos, fiables y disponibles en varios estilos para adaptarse a sus necesidades.'),
-- Chinese Translations
(1, 'zh', '分段提升门', 'fen-duan-ti-sheng-men', '我们的分段门经过精心设计，具有高可靠性、安全性和出色的隔热性能。提供多种设计和饰面，完美匹配您的家庭或工业设施。', '高品质分段门 | 安全隔热 | DoorHan', '了解我们的优质分段门，提供卓越的隔热、强大的安全性和现代化的设计。是住宅车库和工业应用的理想选择。'),
(2, 'zh', '卷帘门', 'juan-lian-men', 'DoorHan卷帘门是一种紧凑耐用的解决方案，非常适用于空间有限的应用场景。它们为车库、仓库和零售店面提供可靠的安全保障。', '耐用型卷帘门 | 节省空间且安全 | DoorHan', '探索我们节省空间且安全的卷帘门。为耐用性和高性能而打造，是商业和住宅物业的理想选择。'),
(3, 'zh', '快速门', 'kuai-su-men', '使用我们的快速门提高效率并保持稳定的气候条件。专为工业和商业环境中的高强度使用而设计，确保优化的交通流量和节能效果。', '工业快速门 | 高效可靠 | DoorHan', '通过DoorHan快速门优化您的运营。专为要求严苛的工业环境中的速度、可靠性和能源效率而设计。'),
(4, 'zh', '折叠门', 'zhe-die-men', '我们的工业折叠门是飞机库和大型仓库入口等超大洞口的完美解决方案。它们提供坚固的结构和可靠的性能。', '适用于大型洞口的工业折叠门 | DoorHan', '安全多功能的工业折叠门，专为超大洞口设计。了解我们为飞机库、造船厂和工业设施提供的坚固可靠的解决方案。'),
(5, 'zh', '平移门', 'ping-yi-men', '通过我们的平移门系列，实现您财产的自动化和安全保障。我们为住宅、商业和工业应用提供可靠且美观的解决方案。', '自动平移门 | 安全便捷 | DoorHan', '通过我们的自动平移门，提升您财产的安全性和便利性。耐用、可靠，并提供多种风格以满足您的需求。');

-- Products
INSERT INTO `products` (`id`, `status`) VALUES
(1, 'active'), (2, 'active'), (3, 'active'), (4, 'active'), (5, 'active'),
(6, 'active'), (7, 'active'), (8, 'active'), (9, 'active');

INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES
(1, 'en', 'Sectional Door RSD01', 'sectional-door-rsd01', '<p>The RSD01 sectional door is a classic and affordable solution for residential garages. It combines a traditional design with robust construction and reliable components, ensuring long-term performance. The panels are filled with polyurethane foam for effective insulation.</p>', 'Affordable Sectional Garage Door RSD01 | DoorHan', 'The RSD01 is a reliable and cost-effective sectional garage door with a classic design. Get a quote for this durable and insulated solution today!', '3000 mm', '2700 mm', '40 mm', 'Polyurethane'),
(2, 'en', 'Sectional Door RSD02', 'sectional-door-rsd02', '<p>The RSD02 is a premium sectional door featuring thick sandwich panels for superior thermal and acoustic insulation. It is the perfect choice for heated garages or workshops, offering maximum energy efficiency and a sleek, modern appearance.</p>', 'Premium Insulated Sectional Door RSD02 | DoorHan', 'Experience superior thermal insulation and security with the RSD02 sectional door. Its 40mm panels make it ideal for heated garages and modern homes.', '6000 mm', '3100 mm', '40 mm', 'Polyurethane'),
(3, 'en', 'Roller Shutter RH77', 'roller-shutter-rh77', '<p>The RH77 roller shutter is a versatile security door constructed from strong steel profiles. Its space-saving design makes it ideal for garages with limited headroom, as well as for securing retail storefronts and commercial premises.</p>', 'Secure Steel Roller Shutter Door RH77 | DoorHan', 'The RH77 is a compact and highly secure roller shutter door. Made from durable steel, it’s a perfect security solution for garages and retail spaces.', '5000 mm', '4000 mm', '19 mm', 'None'),
(4, 'en', 'High Speed Door D-313', 'high-speed-door-d313', '<p>The D-313 is a flexible high-speed PVC roll-up door designed for interior applications. It enhances workflow, separates working areas, and helps maintain climate control, making it essential for logistics, food, and pharmaceutical industries.</p>', 'Interior High-Speed PVC Door D-313 | DoorHan', 'Improve logistics and climate control with the D-313 high-speed door. This fast and reliable PVC door is designed for intensive interior use.', '4000 mm', '4000 mm', 'N/A', 'PVC'),
(5, 'en', 'Industrial Sectional Door ISD01', 'industrial-sectional-door-isd01', '<p>The ISD01 is a heavy-duty sectional door engineered for industrial environments. It is built with reinforced components to withstand intensive use in warehouses, loading docks, and production facilities, offering maximum durability and security.</p>', 'Heavy-Duty Industrial Sectional Door ISD01 | DoorHan', 'The ISD01 is a robust and secure sectional door for all types of industrial buildings. Designed for large openings and intensive operation cycles.', '8000 mm', '7000 mm', '40 mm', 'Polyurethane'),
(6, 'en', 'Yett 01', 'yett-01', '<p>The Yett 01 garage door combines a contemporary aesthetic with user-friendly installation. It is an excellent choice for modern homes, offering a balance of style, functionality, and affordability. The door is delivered as a pre-assembled kit for easy DIY installation.</p>', 'Modern DIY Garage Door Yett 01 | DoorHan', 'Yett 01 delivers a perfect mix of modern design, security, and affordability. This easy-to-install kit is the ideal choice for residential garages.', '3000 mm', '2700 mm', '40 mm', 'Polyurethane'),
(7, 'en', 'Yett 02', 'yett-02', '<p>The Yett 02 series represents our premium residential garage door solution. With superior insulation, a wide range of exclusive finishes, and enhanced security features, the Yett 02 is the ultimate choice for homeowners seeking the best in quality and design.</p>', 'Premium Insulated Residential Door Yett 02 | DoorHan', 'Keep your garage warm and secure with the Yett 02. This premium door features superior insulation, a high-end finish, and advanced security.', '5500 mm', '3000 mm', '40 mm', 'Polyurethane'),
(8, 'en', 'Folding Gate', 'folding-gate', '<p>Our industrial folding gates are custom-built to close extra-large openings in facilities like aircraft hangars, shipyards, and railway depots. Their robust design ensures reliable operation even in the most demanding conditions, allowing for maximum clear width.</p>', 'Custom Industrial Folding Gates for Hangars | DoorHan', 'Our industrial folding gates are the definitive solution for extra-large openings. Custom-engineered for reliability in aircraft hangars and shipyards.', '30000 mm', '8000 mm', 'N/A', 'Mineral Wool'),
(9, 'en', 'Sliding Gate DIY', 'sliding-gate-diy', '<p>This all-in-one DIY kit includes everything you need to install a self-supporting sliding gate. The kit is designed for easy assembly and installation, providing a modern, reliable, and cost-effective solution for automating your driveway entrance.</p>', 'Complete DIY Sliding Gate Kit | Easy Installation | DoorHan', 'Get our complete DIY kit to easily install a modern and reliable sliding gate. This all-in-one package is perfect for residential property access.', '4500 mm', '2200 mm', 'N/A', 'None'),
-- Spanish Translations
(1, 'es', 'Puerta Seccional RSD01', 'puerta-seccional-rsd01', '<p>La puerta seccional RSD01 es una solución clásica y asequible para garajes residenciales. Combina un diseño tradicional con una construcción robusta y componentes fiables, garantizando un rendimiento a largo plazo. Los paneles están rellenos de espuma de poliuretano para un aislamiento eficaz.</p>', 'Puerta de Garaje Seccional Asequible RSD01 | DoorHan', 'La RSD01 es una puerta de garaje seccional fiable y económica con un diseño clásico. ¡Pida hoy mismo un presupuesto para esta solución duradera y aislante!', '3000 mm', '2700 mm', '40 mm', 'Poliuretano'),
(2, 'es', 'Puerta Seccional RSD02', 'puerta-seccional-rsd02', '<p>La RSD02 es una puerta seccional de gama alta con paneles sándwich gruesos para un aislamiento térmico y acústico superior. Es la opción perfecta para garajes o talleres con calefacción, ya que ofrece la máxima eficiencia energética y un aspecto elegante y moderno.</p>', 'Puerta Seccional Premium Aislante RSD02 | DoorHan', 'Experimente un aislamiento térmico y una seguridad superiores con la puerta seccional RSD02. Sus paneles de 40 mm la hacen ideal para garajes con calefacción y hogares modernos.', '6000 mm', '3100 mm', '40 mm', 'Poliuretano'),
(3, 'es', 'Puerta Enrollable RH77', 'puerta-enrollable-rh77', '<p>La persiana enrollable RH77 es una versátil puerta de seguridad fabricada con resistentes perfiles de acero. Su diseño compacto la hace ideal para garajes con altura libre limitada, así como para proteger escaparates y locales comerciales.</p>', 'Puerta Enrollable de Acero Segura RH77 | DoorHan', 'La RH77 es una puerta enrollable compacta y de alta seguridad. Fabricada en acero duradero, es una solución de seguridad perfecta para garajes y locales comerciales.', '5000 mm', '4000 mm', '19 mm', 'Ninguno'),
(4, 'es', 'Puerta Rápida D-313', 'puerta-rapida-d313', '<p>La D-313 es una puerta enrollable de PVC flexible de alta velocidad diseñada para aplicaciones interiores. Mejora el flujo de trabajo, separa áreas de trabajo y ayuda a mantener el control climático, por lo que es esencial para las industrias de logística, alimentaria y farmacéutica.</p>', 'Puerta Rápida de PVC para Interiores D-313 | DoorHan', 'Mejore la logística y el control climático con la puerta rápida D-313. Esta puerta de PVC rápida y fiable está diseñada para un uso interior intensivo.', '4000 mm', '4000 mm', 'N/A', 'PVC'),
(5, 'es', 'Puerta Seccional Industrial ISD01', 'puerta-seccional-industrial-isd01', '<p>La ISD01 es una puerta seccional de alta resistencia diseñada para entornos industriales. Está construida con componentes reforzados para soportar un uso intensivo en almacenes, muelles de carga e instalaciones de producción, ofreciendo la máxima durabilidad y seguridad.</p>', 'Puerta Seccional Industrial de Alta Resistencia ISD01 | DoorHan', 'La ISD01 es una puerta seccional robusta y segura para todo tipo de edificios industriales. Diseñada para grandes aperturas y ciclos de funcionamiento intensivos.', '8000 mm', '7000 mm', '40 mm', 'Poliuretano'),
(6, 'es', 'Yett 01', 'yett-01', '<p>La puerta de garaje Yett 01 combina una estética contemporánea con una instalación sencilla. Es una excelente opción para hogares modernos, ya que ofrece un equilibrio entre estilo, funcionalidad y asequibilidad. La puerta se entrega como un kit premontado para facilitar la instalación por parte del usuario.</p>', 'Puerta de Garaje Moderna DIY Yett 01 | DoorHan', 'Yett 01 ofrece una mezcla perfecta de diseño moderno, seguridad y asequibilidad. Este kit de fácil instalación es la opción ideal para garajes residenciales.', '3000 mm', '2700 mm', '40 mm', 'Poliuretano'),
(7, 'es', 'Yett 02', 'yett-02', '<p>La serie Yett 02 representa nuestra solución de puertas de garaje residenciales de primera calidad. Con un aislamiento superior, una amplia gama de acabados exclusivos y características de seguridad mejoradas, la Yett 02 es la opción definitiva para los propietarios que buscan lo mejor en calidad y diseño.</p>', 'Puerta Residencial Premium Aislante Yett 02 | DoorHan', 'Mantenga su garaje cálido y seguro con la Yett 02. Esta puerta de primera calidad cuenta con un aislamiento superior, un acabado de alta gama y seguridad avanzada.', '5500 mm', '3000 mm', '40 mm', 'Poliuretano'),
(8, 'es', 'Portón Plegable', 'porton-plegable', '<p>Nuestros portones plegables industriales se fabrican a medida para cerrar aberturas extragrandes en instalaciones como hangares de aviones, astilleros y cocheras de ferrocarril. Su robusto diseño garantiza un funcionamiento fiable incluso en las condiciones más exigentes, permitiendo la máxima anchura libre.</p>', 'Portones Plegables Industriales a Medida para Hangares | DoorHan', 'Nuestros portones plegables industriales son la solución definitiva para aberturas extragrandes. Diseñados a medida para garantizar su fiabilidad en hangares de aviones y astilleros.', '30000 mm', '8000 mm', 'N/A', 'Lana mineral'),
(9, 'es', 'Portón Corredero DIY', 'porton-corredero-diy', '<p>Este kit todo en uno de bricolaje incluye todo lo que necesita para instalar un portón corredero autoportante. El kit está diseñado para un fácil montaje e instalación, proporcionando una solución moderna, fiable y rentable para automatizar la entrada de su vehículo.</p>', 'Kit Completo de Portón Corredero DIY | Fácil Instalación | DoorHan', 'Consiga nuestro completo kit de bricolaje para instalar fácilmente un portón corredero moderno y fiable. Este paquete todo en uno es perfecto para el acceso a propiedades residenciales.', '4500 mm', '2200 mm', 'N/A', 'Ninguno'),
-- Chinese Translations
(1, 'zh', '分段门 RSD01', 'fen-duan-men-rsd01', '<p>RSD01分段门是住宅车库的经典且经济实惠的解决方案。它结合了传统设计、坚固的结构和可靠的组件，确保长期性能。门板填充有聚氨酯泡沫，以实现有效的隔热。</p>', '经济实惠的分段车库门 RSD01 | DoorHan', 'RSD01是一款可靠且经济高效的分段车库门，采用经典设计。立即获取这款耐用隔热解决方案的报价！', '3000 mm', '2700 mm', '40 mm', '聚氨酯'),
(2, 'zh', '分段门 RSD02', 'fen-duan-men-rsd02', '<p>RSD02是一款优质分段门，采用厚夹芯板，具有卓越的隔热和隔音性能。它是加热车库或车间的完美选择，提供最大的能源效率和时尚现代的外观。</p>', '优质隔热分段门 RSD02 | DoorHan', '体验RSD02分段门卓越的隔热和安全性能。其40毫米厚的门板使其成为加热车库和现代家庭的理想选择。', '6000 mm', '3100 mm', '40 mm', '聚氨酯'),
(3, 'zh', '卷帘门 RH77', 'juan-lian-men-rh77', '<p>RH77卷帘门是由坚固的钢型材构成的多功能安全门。其节省空间的设计使其非常适用于净空有限的车库，以及保护零售店面和商业场所。</p>', '安全钢制卷帘门 RH77 | DoorHan', 'RH77是一款紧凑且高度安全的卷帘门。由耐用钢材制成，是车库和零售空间的完美安全解决方案。', '5000 mm', '4000 mm', '19 mm', '无'),
(4, 'zh', '快速门 D-313', 'kuai-su-men-d313', '<p>D-313是专为室内应用设计的柔性高速PVC卷帘门。它能改善工作流程、分隔工作区域并帮助维持气候控制，使其成为物流、食品和制药行业必不可少的设备。</p>', '室内高速PVC门 D-313 | DoorHan', '使用D-313高速门改善物流和气候控制。这款快速可靠的PVC门专为高强度室内使用而设计。', '4000 mm', '4000 mm', 'N/A', 'PVC'),
(5, 'zh', '工业分段门 ISD01', 'gong-ye-fen-duan-men-isd01', '<p>ISD01是专为工业环境设计的重型分段门。它采用加固组件制造，可承受仓库、装卸平台和生产设施的高强度使用，提供最大的耐用性和安全性。</p>', '重型工业分段门 ISD01 | DoorHan', 'ISD01是适用于所有类型工业建筑的坚固安全的分段门。专为大型洞口和高强度操作循环而设计。', '8000 mm', '7000 mm', '40 mm', '聚氨酯'),
(6, 'zh', 'Yett 01', 'yett-01', '<p>Yett 01车库门将现代美学与用户友好的安装相结合。它是现代家庭的绝佳选择，实现了风格、功能和经济性的平衡。该门以预组装套件形式交付，便于自行安装。</p>', '现代DIY车库门 Yett 01 | DoorHan', 'Yett 01完美融合了现代设计、安全性和经济性。这款易于安装的套件是住宅车库的理想选择。', '3000 mm', '2700 mm', '40 mm', '聚氨酯'),
(7, 'zh', 'Yett 02', 'yett-02', '<p>Yett 02系列代表了我们的优质住宅车库门解决方案。凭借卓越的隔热性能、多种独特的饰面和增强的安全功能，Yett 02是追求最佳质量和设计的房主的终极选择。', '优质隔热住宅门 Yett 02 | DoorHan', '使用Yett 02让您的车库保持温暖和安全。这款优质门具有卓越的隔热性能、高端饰面和先进的安全性。', '5500 mm', '3000 mm', '40 mm', '聚氨酯'),
(8, 'zh', '折叠门', 'zhe-die-men', '<p>我们的工业折叠门是为飞机库、造船厂和铁路车库等设施中的超大洞口定制的。其坚固的设计确保即使在最苛刻的条件下也能可靠运行，并允许最大的净宽度。', '定制机库工业折叠门 | DoorHan', '我们的工业折叠门是超大洞口的终极解决方案。为飞机库和造船厂的可靠性而定制设计。', '30000 mm', '8000 mm', 'N/A', '矿棉'),
(9, 'zh', '平移门DIY', 'ping-yi-men-diy', '<p>这款一体化DIY套件包含安装自支撑平移门所需的一切。该套件设计用于轻松组装和安装，为自动化您的车道入口提供了一个现代、可靠且经济高效的解决方案。', '完整DIY平移门套件 | 安装简便 | DoorHan', '获取我们完整的DIY套件，轻松安装现代可靠的平移门。这款一体化套装非常适合住宅物业的入口。', '4500 mm', '2200 mm', 'N/A', '无');

-- Product-category mapping
INSERT INTO `product_categories` (`product_id`, `category_id`, `is_primary`) VALUES
(1, 1, 1), (2, 1, 1), (3, 2, 1), (4, 3, 1), (5, 1, 1), (6, 1, 1), (7, 1, 1), (8, 4, 1), (9, 5, 1);

-- Posts
INSERT INTO `posts` (`id`, `status`, `created_at`, `image`, `image2`, `image3`) VALUES
(1, 'published', '2023-10-26 10:00:00', 'news1.jpg', 'news1-2.jpg', NULL),
(2, 'published', '2023-10-27 11:00:00', 'news2.jpg', NULL, NULL),
(3, 'published', '2023-10-28 12:00:00', 'news3.jpg', 'news3-2.jpg', 'news3-3.jpg');

INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES
(1, 'en', 'DoorHan Launches New Line of Premium Residential Doors', 'new-premium-residential-doors', '<p>We are thrilled to announce the launch of our new Yett series, a premium line of residential garage doors. Combining cutting-edge technology with sophisticated design, the Yett series offers homeowners unparalleled security, insulation, and style. Visit our products page to explore the new collection.</p>', 'DoorHan Launches New Yett Series of Premium Garage Doors', 'Discover the new Yett series from DoorHan. A premium line of residential garage doors offering advanced security, superior insulation, and modern design.'),
(2, 'en', 'Visit DoorHan at the International Construction Exhibition 2023', 'doorhan-at-construction-exhibition-2023', '<p>DoorHan is excited to confirm its participation in the International Construction Exhibition 2023. We will be showcasing our latest innovations in industrial doors and automation systems. Join us at booth #42B to see live demonstrations and speak with our experts.</p>', 'Meet DoorHan at the International Construction Exhibition 2023', 'Join DoorHan at the International Construction Exhibition 2023. Visit booth #42B to discover our latest innovations in industrial doors and automation.'),
(3, 'en', 'Essential Maintenance Tips for Your Garage Door', 'essential-garage-door-maintenance-tips', '<p>Proper maintenance is key to ensuring the longevity and safe operation of your garage door. In this post, we share essential tips, from lubricating moving parts to checking the balance. Following these simple steps can prevent costly repairs and extend the life of your door.</p>', 'Top Maintenance Tips for a Long-Lasting Garage Door | DoorHan', 'Learn how to properly maintain your garage door with our essential tips. Ensure safety, prevent costly repairs, and extend the life of your door with these simple steps.'),
-- Spanish Translations
(1, 'es', 'DoorHan Lanza Nueva Línea de Puertas Residenciales Premium', 'nueva-linea-puertas-residenciales-premium', '<p>Estamos encantados de anunciar el lanzamiento de nuestra nueva serie Yett, una línea premium de puertas de garaje residenciales. Combinando tecnología de vanguardia con un diseño sofisticado, la serie Yett ofrece a los propietarios una seguridad, aislamiento y estilo inigualables. Visite nuestra página de productos para explorar la nueva colección.</p>', 'DoorHan Lanza la Nueva Serie Yett de Puertas de Garaje Premium', 'Descubra la nueva serie Yett de DoorHan. Una línea premium de puertas de garaje residenciales que ofrece seguridad avanzada, aislamiento superior y diseño moderno.'),
(2, 'es', 'Visite a DoorHan en la Exposición Internacional de la Construcción 2023', 'doorhan-en-exposicion-internacional-construccion-2023', '<p>DoorHan se complace en confirmar su participación en la Exposición Internacional de la Construcción 2023. Estaremos presentando nuestras últimas innovaciones en puertas industriales y sistemas de automatización. Visítenos en el stand #42B para ver demostraciones en vivo y hablar con nuestros expertos.</p>', 'Encuentre a DoorHan en la Exposición Internacional de la Construcción 2023', 'Únase a DoorHan en la Exposición Internacional de la Construcción 2023. Visite el stand #42B para descubrir nuestras últimas innovaciones en puertas industriales y automatización.'),
(3, 'es', 'Consejos Esenciales para el Mantenimiento de su Puerta de Garaje', 'consejos-esenciales-mantenimiento-puerta-garaje', '<p>Un mantenimiento adecuado es clave para garantizar la longevidad y el funcionamiento seguro de su puerta de garaje. En esta publicación, compartimos consejos esenciales, desde la lubricación de las piezas móviles hasta la comprobación del equilibrio. Seguir estos sencillos pasos puede evitar reparaciones costosas y prolongar la vida útil de su puerta.</p>', 'Los Mejores Consejos de Mantenimiento para una Puerta de Garaje Duradera | DoorHan', 'Aprenda a mantener adecuadamente su puerta de garaje con nuestros consejos esenciales. Garantice la seguridad, evite reparaciones costosas y prolongue la vida útil de su puerta con estos sencillos pasos.'),
-- Chinese Translations
(1, 'zh', 'DoorHan推出全新高端住宅门系列', '全新高端住宅门系列', '<p>我们非常激动地宣布推出全新的Yett系列高端住宅车库门。Yett系列将尖端技术与精致设计相结合，为房主提供无与伦比的安全性、隔热性和风格。请访问我们的产品页面，探索新系列。', 'DoorHan推出全新Yett系列高端车库门', '探索DoorHan全新的Yett系列。一个提供先进安全性、卓越隔热性和现代设计的高端住宅车库门系列。'),
(2, 'zh', '欢迎参观2023年国际建筑展览会的DoorHan展台', 'doorhan-2023-国际建筑展览会', '<p>DoorHan很高兴地确认将参加2023年国际建筑展览会。我们将展示我们在工业门和自动化系统方面的最新创新。欢迎莅临42B展台观看现场演示并与我们的专家交流。', '在2023年国际建筑展览会与DoorHan会面', '欢迎参加2023年国际建筑展览会的DoorHan展台。请访问42B展台，了解我们在工业门和自动化领域的最新创新。'),
(3, 'zh', '车库门基本维护技巧', '车库门基本维护技巧', '<p>适当的维护是确保车库门使用寿命和安全运行的关键。在这篇文章中，我们分享了从润滑活动部件到检查平衡等基本技巧。遵循这些简单的步骤可以避免昂贵的维修，并延长您门的使用寿命。', '延长车库门使用寿命的最佳维护技巧 | DoorHan', '通过我们的基本技巧，了解如何正确维护您的车库门。通过这些简单的步骤，确保安全，避免昂贵的维修，并延长您门的使用寿命。');

-- Settings
INSERT INTO `settings` (`key`, `value`) VALUES
('site_title', 'DoorHan'),
('contact_email', 'info@doorhan.com'),
('footer_about', 'DoorHan is a leading global manufacturer of gates, doors, and automation systems, offering innovative and reliable solutions for over 30 years.'),
('facebook_url', 'https://www.facebook.com/DoorHan'),
('linkedin_url', 'https://www.linkedin.com/company/doorhan'),
('youtube_url', 'https://www.youtube.com/user/DoorHan');

-- Administrator (password: P@ssw0rd123!)
INSERT INTO `users` (`username`, `password`, `role`) VALUES
('admin', '$2y$10$xH0YiKX4gw55ZIL2Z3KVOe3PPocrQCg75yAZv7zeHb2zB6lkqWNX6', 'admin');

-- Navigation items
INSERT INTO `navigation_items` (`title`, `url`, `parent_id`, `menu_order`) VALUES
('Home', '/', NULL, 1),
('Products', '/products', NULL, 2),
('News', '/news', NULL, 3),
('About', '/about', NULL, 4),
('Contact', '/contact', NULL, 5);
