-- Seed data for i18n schema

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `product_categories`;
TRUNCATE TABLE `product_images`;
TRUNCATE TABLE `product_translations`;
TRUNCATE TABLE `products`;
TRUNCATE TABLE `category_translations`;
TRUNCATE TABLE `categories`;
TRUNCATE TABLE `post_translations`;
TRUNCATE TABLE `posts`;
TRUNCATE TABLE `settings`;
TRUNCATE TABLE `users`;
TRUNCATE TABLE `navigation_items`;
TRUNCATE TABLE `page_translations`;
TRUNCATE TABLE `pages`;
SET FOREIGN_KEY_CHECKS = 1;

-- Categories
INSERT INTO `categories` (`id`, `parent_id`) VALUES (1, NULL), (2, NULL), (3, NULL), (4, NULL), (5, NULL);
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES
(1, 'en', 'Sectional Doors', 'sectional-doors', '', 'Sectional Garage Doors | DoorHan', 'Modern and efficient sectional garage doors that provide excellent insulation and security.'),
(2, 'en', 'Roller Shutter Doors', 'roller-shutter-doors', '', 'Roller Shutter Garage Doors | DoorHan', 'Space-saving and durable roller shutter doors, ideal for garages with limited headroom.'),
(3, 'en', 'High Speed Doors', 'high-speed-doors', '', 'High-Speed Industrial Doors | DoorHan', 'Optimize your workflow with our fast and reliable high-speed industrial doors.'),
(4, 'en', 'Folding Doors', 'folding-doors', '', 'Industrial Folding Doors | DoorHan', 'Versatile and robust folding doors for large openings in industrial facilities.'),
(5, 'en', 'Sliding Gates', 'sliding-gates', '', 'Sliding Gates | DoorHan', 'Automatic sliding gates for secure and convenient access to your property.');

-- Products
INSERT INTO `products` (`id`, `status`) VALUES
(1, 'active'), (2, 'active'), (3, 'active'), (4, 'active'), (5, 'active'),
(6, 'active'), (7, 'active'), (8, 'active'), (9, 'active');

INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES
(1, 'en', 'Sectional Door RSD01', 'sectional-door-rsd01', '<p>The RSD01 sectional door is a reliable and durable solution for your garage. It offers a classic design with robust construction.</p>', 'Sectional Door RSD01 | DoorHan', 'The RSD01 is a reliable and durable sectional garage door. Get a quote today!', '3000 mm', '2700 mm', '40 mm', 'Polyurethane'),
(2, 'en', 'Sectional Door RSD02', 'sectional-door-rsd02', '<p>The RSD02 sectional door offers excellent thermal insulation thanks to its sandwich panels. Perfect for heated garages.</p>', 'Insulated Sectional Door RSD02 | DoorHan', 'The RSD02 sectional door provides excellent thermal insulation and security for your garage.', '6000 mm', '3100 mm', '40 mm', 'Polyurethane'),
(3, 'en', 'Roller Shutter RH77', 'roller-shutter-rh77', '<p>A compact and convenient roller shutter door made of steel profiles. Ideal for garages and retail spaces.</p>', 'Roller Shutter Door RH77 | DoorHan', 'The RH77 is a compact and secure roller shutter door, perfect for various applications.', '5000 mm', '4000 mm', '19 mm', 'None'),
(4, 'en', 'High Speed Door D-313', 'high-speed-door-d313', '<p>A high-speed PVC door for intensive use in interior spaces. It helps to maintain climate control and workflow.</p>', 'High Speed Door D-313 | DoorHan', 'The D-313 is a high-speed door designed for intensive use in industrial and commercial environments.', '4000 mm', '4000 mm', 'N/A', 'PVC'),
(5, 'en', 'Industrial Sectional Door ISD01', 'industrial-sectional-door-isd01', '<p>A robust sectional door for industrial applications. It is designed for large openings and intensive use.</p>', 'Industrial Sectional Door ISD01 | DoorHan', 'The ISD01 is a robust and reliable sectional door for all types of industrial buildings.', '8000 mm', '7000 mm', '40 mm', 'Polyurethane'),
(6, 'en', 'Yett 01', 'yett-01', '<p>Yett 01 is a great choice for residential garages. It features a modern design and is easy to install.</p>', 'Yett 01 Residential Door | DoorHan', 'Yett 01 offers the perfect balance of modern design, security, and affordability for your home.', '3000 mm', '2700 mm', '40 mm', 'Polyurethane'),
(7, 'en', 'Yett 02', 'yett-02', '<p>Yett 02 provides superior insulation and a premium finish. It is the top choice for modern homes.</p>', 'Yett 02 Insulated Residential Door | DoorHan', 'Keep your garage warm and secure with the Yett 02, featuring superior insulation properties.', '5500 mm', '3000 mm', '40 mm', 'Polyurethane'),
(8, 'en', 'Folding Gate', 'folding-gate', '<p>Industrial folding gate for hangars and depots. Allows for maximum opening width.</p>', 'Industrial Folding Gate | DoorHan', 'Our industrial folding gates are the perfect solution for extra-large openings like aircraft hangars.', '30000 mm', '8000 mm', 'N/A', 'Mineral Wool'),
(9, 'en', 'Sliding Gate DIY', 'sliding-gate-diy', '<p>A complete DIY kit for a self-supporting sliding gate. Easy to assemble and install.</p>', 'DIY Sliding Gate Kit | DoorHan', 'Get our complete DIY kit to easily install a modern and reliable sliding gate on your property.', '4500 mm', '2200 mm', 'N/A', 'None');

-- Product-category mapping
INSERT INTO `product_categories` (`product_id`, `category_id`, `is_primary`) VALUES
(1, 1, 1), (2, 1, 1), (3, 2, 1), (4, 3, 1), (5, 1, 1), (6, 1, 1), (7, 1, 1), (8, 4, 1), (9, 5, 1);

-- Posts
INSERT INTO `posts` (`id`, `status`, `created_at`) VALUES
(1, 'published', '2023-10-26 10:00:00'),
(2, 'published', '2023-10-27 11:00:00'),
(3, 'draft', '2023-10-28 12:00:00');

INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES
(1, 'en', 'New Product Line', 'new-product-line', '<p>We are excited to announce our new product line.</p>', 'New Product Line', 'We are excited to announce our new product line.'),
(2, 'en', 'DoorHan at Exhibition', 'doorhan-at-exhibition', '<p>DoorHan will be participating in the upcoming construction exhibition.</p>', 'DoorHan at Exhibition', 'DoorHan will be participating in the upcoming construction exhibition.'),
(3, 'en', 'Maintenance Tips', 'maintenance-tips', '<p>Here are some tips for maintaining your garage door.</p>', 'Maintenance Tips', 'Here are some tips for maintaining your garage door.');

-- Settings
INSERT INTO `settings` (`key`, `value`) VALUES
('site_title', 'DoorHan'),
('contact_email', 'admin@doorhan.com'),
('footer_about', 'DoorHan is a leading global manufacturer of gates, doors, and automation systems, offering innovative and reliable solutions for over 30 years.'),
('facebook_url', 'https://www.facebook.com/DoorHan'),
('linkedin_url', 'https://www.linkedin.com/company/doorhan'),
('youtube_url', 'https://www.youtube.com/user/DoorHan');

-- Administrator (password: P@ssw0rd123!)
INSERT INTO `users` (`username`, `password`, `role`) VALUES
('admin', '$2y$10$xH0YiKX4gw55ZIL2Z3KVOe3PPocrQCg75yAZv7zeHb2zB6lkqWNX6', 'admin');

-- Navigation items
INSERT INTO `navigation_items` (`title`, `url`, `parent_id`, `menu_order`) VALUES
('Home', '/', NULL, 1),
('Products', '/products', NULL, 2),
('News', '/news', NULL, 3),
('About', '/about', NULL, 4),
('Contact', '/contact', NULL, 5);

-- Translations for other languages
-- Product Translations
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (1, 'es', 'Puerta Seccional RSD01', 'sectional-door-rsd01-es', '<p>The RSD01 sectional door is a reliable and durable solution for your garage.</p>', 'Puerta Seccional RSD01 | DoorHan', 'The RSD01 is a reliable and durable sectional garage door. Get a quote today!', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (1, 'zh', '分段门 RSD01', 'sectional-door-rsd01-zh', '<p>The RSD01 sectional door is a reliable and durable solution for your garage.</p>', '分段门 RSD01 | DoorHan', 'The RSD01 is a reliable and durable sectional garage door. Get a quote today!', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (1, 'fr', 'Porte Sectionnelle RSD01', 'sectional-door-rsd01-fr', '<p>The RSD01 sectional door is a reliable and durable solution for your garage.</p>', 'Porte Sectionnelle RSD01 | DoorHan', 'The RSD01 is a reliable and durable sectional garage door. Get a quote today!', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (1, 'ar', 'باب مقطعي RSD01', 'sectional-door-rsd01-ar', '<p>The RSD01 sectional door is a reliable and durable solution for your garage.</p>', 'باب مقطعي RSD01 | DoorHan', 'The RSD01 is a reliable and durable sectional garage door. Get a quote today!', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (1, 'pt', 'Porta Seccional RSD01', 'sectional-door-rsd01-pt', '<p>The RSD01 sectional door is a reliable and durable solution for your garage.</p>', 'Porta Seccional RSD01 | DoorHan', 'The RSD01 is a reliable and durable sectional garage door. Get a quote today!', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (1, 'de', 'Sektionaltor RSD01', 'sectional-door-rsd01-de', '<p>The RSD01 sectional door is a reliable and durable solution for your garage.</p>', 'Sektionaltor RSD01 | DoorHan', 'The RSD01 is a reliable and durable sectional garage door. Get a quote today!', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (1, 'hi', 'अनुभागीय दरवाजा RSD01', 'sectional-door-rsd01-hi', '<p>The RSD01 sectional door is a reliable and durable solution for your garage.</p>', 'अनुभागीय दरवाजा RSD01 | DoorHan', 'The RSD01 is a reliable and durable sectional garage door. Get a quote today!', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (1, 'id', 'Pintu Sectional RSD01', 'sectional-door-rsd01-id', '<p>The RSD01 sectional door is a reliable and durable solution for your garage.</p>', 'Pintu Sectional RSD01 | DoorHan', 'The RSD01 is a reliable and durable sectional garage door. Get a quote today!', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (1, 'ja', 'セクショナルドア RSD01', 'sectional-door-rsd01-ja', '<p>The RSD01 sectional door is a reliable and durable solution for your garage.</p>', 'セクショナルドア RSD01 | DoorHan', 'The RSD01 is a reliable and durable sectional garage door. Get a quote today!', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (1, 'ko', '섹션 도어 RSD01', 'sectional-door-rsd01-ko', '<p>The RSD01 sectional door is a reliable and durable solution for your garage.</p>', '섹션 도어 RSD01 | DoorHan', 'The RSD01 is a reliable and durable sectional garage door. Get a quote today!', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (1, 'it', 'Porta Sezionale RSD01', 'sectional-door-rsd01-it', '<p>The RSD01 sectional door is a reliable and durable solution for your garage.</p>', 'Porta Sezionale RSD01 | DoorHan', 'The RSD01 is a reliable and durable sectional garage door. Get a quote today!', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (2, 'es', 'Puerta Seccional RSD02', 'sectional-door-rsd02-es', '<p>The RSD02 sectional door offers excellent thermal insulation thanks to its sandwich panels.</p>', 'Puerta Seccional RSD02 | DoorHan', 'The RSD02 sectional door provides excellent thermal insulation and security for your garage.', '6000 mm', '3100 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (2, 'zh', '分段门 RSD02', 'sectional-door-rsd02-zh', '<p>The RSD02 sectional door offers excellent thermal insulation thanks to its sandwich panels.</p>', '分段门 RSD02 | DoorHan', 'The RSD02 sectional door provides excellent thermal insulation and security for your garage.', '6000 mm', '3100 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (2, 'fr', 'Porte Sectionnelle RSD02', 'sectional-door-rsd02-fr', '<p>The RSD02 sectional door offers excellent thermal insulation thanks to its sandwich panels.</p>', 'Porte Sectionnelle RSD02 | DoorHan', 'The RSD02 sectional door provides excellent thermal insulation and security for your garage.', '6000 mm', '3100 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (2, 'ar', 'باب مقطعي RSD02', 'sectional-door-rsd02-ar', '<p>The RSD02 sectional door offers excellent thermal insulation thanks to its sandwich panels.</p>', 'باب مقطعي RSD02 | DoorHan', 'The RSD02 sectional door provides excellent thermal insulation and security for your garage.', '6000 mm', '3100 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (2, 'pt', 'Porta Seccional RSD02', 'sectional-door-rsd02-pt', '<p>The RSD02 sectional door offers excellent thermal insulation thanks to its sandwich panels.</p>', 'Porta Seccional RSD02 | DoorHan', 'The RSD02 sectional door provides excellent thermal insulation and security for your garage.', '6000 mm', '3100 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (2, 'de', 'Sektionaltor RSD02', 'sectional-door-rsd02-de', '<p>The RSD02 sectional door offers excellent thermal insulation thanks to its sandwich panels.</p>', 'Sektionaltor RSD02 | DoorHan', 'The RSD02 sectional door provides excellent thermal insulation and security for your garage.', '6000 mm', '3100 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (2, 'hi', 'अनुभागीय दरवाजा RSD02', 'sectional-door-rsd02-hi', '<p>The RSD02 sectional door offers excellent thermal insulation thanks to its sandwich panels.</p>', 'अनुभागीय दरवाजा RSD02 | DoorHan', 'The RSD02 sectional door provides excellent thermal insulation and security for your garage.', '6000 mm', '3100 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (2, 'id', 'Pintu Sectional RSD02', 'sectional-door-rsd02-id', '<p>The RSD02 sectional door offers excellent thermal insulation thanks to its sandwich panels.</p>', 'Pintu Sectional RSD02 | DoorHan', 'The RSD02 sectional door provides excellent thermal insulation and security for your garage.', '6000 mm', '3100 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (2, 'ja', 'セクショナルドア RSD02', 'sectional-door-rsd02-ja', '<p>The RSD02 sectional door offers excellent thermal insulation thanks to its sandwich panels.</p>', 'セクショナルドア RSD02 | DoorHan', 'The RSD02 sectional door provides excellent thermal insulation and security for your garage.', '6000 mm', '3100 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (2, 'ko', '섹션 도어 RSD02', 'sectional-door-rsd02-ko', '<p>The RSD02 sectional door offers excellent thermal insulation thanks to its sandwich panels.</p>', '섹션 도어 RSD02 | DoorHan', 'The RSD02 sectional door provides excellent thermal insulation and security for your garage.', '6000 mm', '3100 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (2, 'it', 'Porta Sezionale RSD02', 'sectional-door-rsd02-it', '<p>The RSD02 sectional door offers excellent thermal insulation thanks to its sandwich panels.</p>', 'Porta Sezionale RSD02 | DoorHan', 'The RSD02 sectional door provides excellent thermal insulation and security for your garage.', '6000 mm', '3100 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (3, 'es', 'Persiana Enrollable RH77', 'roller-shutter-rh77-es', '<p>A compact and convenient roller shutter door made of steel profiles.</p>', 'Persiana Enrollable RH77 | DoorHan', 'The RH77 is a compact and secure roller shutter door, perfect for various applications.', '5000 mm', '4000 mm', '19 mm', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (3, 'zh', '卷帘门 RH77', 'roller-shutter-rh77-zh', '<p>A compact and convenient roller shutter door made of steel profiles.</p>', '卷帘门 RH77 | DoorHan', 'The RH77 is a compact and secure roller shutter door, perfect for various applications.', '5000 mm', '4000 mm', '19 mm', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (3, 'fr', 'Volet Roulant RH77', 'roller-shutter-rh77-fr', '<p>A compact and convenient roller shutter door made of steel profiles.</p>', 'Volet Roulant RH77 | DoorHan', 'The RH77 is a compact and secure roller shutter door, perfect for various applications.', '5000 mm', '4000 mm', '19 mm', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (3, 'ar', 'مصراع دوار RH77', 'roller-shutter-rh77-ar', '<p>A compact and convenient roller shutter door made of steel profiles.</p>', 'مصراع دوار RH77 | DoorHan', 'The RH77 is a compact and secure roller shutter door, perfect for various applications.', '5000 mm', '4000 mm', '19 mm', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (3, 'pt', 'Persiana de Enrolar RH77', 'roller-shutter-rh77-pt', '<p>A compact and convenient roller shutter door made of steel profiles.</p>', 'Persiana de Enrolar RH77 | DoorHan', 'The RH77 is a compact and secure roller shutter door, perfect for various applications.', '5000 mm', '4000 mm', '19 mm', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (3, 'de', 'Rollladen RH77', 'roller-shutter-rh77-de', '<p>A compact and convenient roller shutter door made of steel profiles.</p>', 'Rollladen RH77 | DoorHan', 'The RH77 is a compact and secure roller shutter door, perfect for various applications.', '5000 mm', '4000 mm', '19 mm', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (3, 'hi', 'रोलर शटर RH77', 'roller-shutter-rh77-hi', '<p>A compact and convenient roller shutter door made of steel profiles.</p>', 'रोलर शटर RH77 | DoorHan', 'The RH77 is a compact and secure roller shutter door, perfect for various applications.', '5000 mm', '4000 mm', '19 mm', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (3, 'id', 'Roller Shutter RH77', 'roller-shutter-rh77-id', '<p>A compact and convenient roller shutter door made of steel profiles.</p>', 'Roller Shutter RH77 | DoorHan', 'The RH77 is a compact and secure roller shutter door, perfect for various applications.', '5000 mm', '4000 mm', '19 mm', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (3, 'ja', 'ローラーシャッター RH77', 'roller-shutter-rh77-ja', '<p>A compact and convenient roller shutter door made of steel profiles.</p>', 'ローラーシャッター RH77 | DoorHan', 'The RH77 is a compact and secure roller shutter door, perfect for various applications.', '5000 mm', '4000 mm', '19 mm', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (3, 'ko', '롤러 셔터 RH77', 'roller-shutter-rh77-ko', '<p>A compact and convenient roller shutter door made of steel profiles.</p>', '롤러 셔터 RH77 | DoorHan', 'The RH77 is a compact and secure roller shutter door, perfect for various applications.', '5000 mm', '4000 mm', '19 mm', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (3, 'it', 'Serranda Avvolgibile RH77', 'roller-shutter-rh77-it', '<p>A compact and convenient roller shutter door made of steel profiles.</p>', 'Serranda Avvolgibile RH77 | DoorHan', 'The RH77 is a compact and secure roller shutter door, perfect for various applications.', '5000 mm', '4000 mm', '19 mm', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (4, 'es', 'Puerta Rápida D-313', 'high-speed-door-d313-es', '<p>A high-speed PVC door for intensive use in interior spaces.</p>', 'Puerta Rápida D-313 | DoorHan', 'The D-313 is a high-speed door designed for intensive use in industrial and commercial environments.', '4000 mm', '4000 mm', 'N/A', 'PVC');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (4, 'zh', '快速门 D-313', 'high-speed-door-d313-zh', '<p>A high-speed PVC door for intensive use in interior spaces.</p>', '快速门 D-313 | DoorHan', 'The D-313 is a high-speed door designed for intensive use in industrial and commercial environments.', '4000 mm', '4000 mm', 'N/A', 'PVC');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (4, 'fr', 'Porte Rapide D-313', 'high-speed-door-d313-fr', '<p>A high-speed PVC door for intensive use in interior spaces.</p>', 'Porte Rapide D-313 | DoorHan', 'The D-313 is a high-speed door designed for intensive use in industrial and commercial environments.', '4000 mm', '4000 mm', 'N/A', 'PVC');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (4, 'ar', 'باب عالي السرعة D-313', 'high-speed-door-d313-ar', '<p>A high-speed PVC door for intensive use in interior spaces.</p>', 'باب عالي السرعة D-313 | DoorHan', 'The D-313 is a high-speed door designed for intensive use in industrial and commercial environments.', '4000 mm', '4000 mm', 'N/A', 'PVC');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (4, 'pt', 'Porta Rápida D-313', 'high-speed-door-d313-pt', '<p>A high-speed PVC door for intensive use in interior spaces.</p>', 'Porta Rápida D-313 | DoorHan', 'The D-313 is a high-speed door designed for intensive use in industrial and commercial environments.', '4000 mm', '4000 mm', 'N/A', 'PVC');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (4, 'de', 'Schnelllauftor D-313', 'high-speed-door-d313-de', '<p>A high-speed PVC door for intensive use in interior spaces.</p>', 'Schnelllauftor D-313 | DoorHan', 'The D-313 is a high-speed door designed for intensive use in industrial and commercial environments.', '4000 mm', '4000 mm', 'N/A', 'PVC');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (4, 'hi', 'हाई स्पीड डोर D-313', 'high-speed-door-d313-hi', '<p>A high-speed PVC door for intensive use in interior spaces.</p>', 'हाई स्पीड डोर D-313 | DoorHan', 'The D-313 is a high-speed door designed for intensive use in industrial and commercial environments.', '4000 mm', '4000 mm', 'N/A', 'PVC');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (4, 'id', 'Pintu Kecepatan Tinggi D-313', 'high-speed-door-d313-id', '<p>A high-speed PVC door for intensive use in interior spaces.</p>', 'Pintu Kecepatan Tinggi D-313 | DoorHan', 'The D-313 is a high-speed door designed for intensive use in industrial and commercial environments.', '4000 mm', '4000 mm', 'N/A', 'PVC');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (4, 'ja', '高速ドア D-313', 'high-speed-door-d313-ja', '<p>A high-speed PVC door for intensive use in interior spaces.</p>', '高速ドア D-313 | DoorHan', 'The D-313 is a high-speed door designed for intensive use in industrial and commercial environments.', '4000 mm', '4000 mm', 'N/A', 'PVC');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (4, 'ko', '고속 도어 D-313', 'high-speed-door-d313-ko', '<p>A high-speed PVC door for intensive use in interior spaces.</p>', '고속 도어 D-313 | DoorHan', 'The D-313 is a high-speed door designed for intensive use in industrial and commercial environments.', '4000 mm', '4000 mm', 'N/A', 'PVC');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (4, 'it', 'Porta Rapida D-313', 'high-speed-door-d313-it', '<p>A high-speed PVC door for intensive use in interior spaces.</p>', 'Porta Rapida D-313 | DoorHan', 'The D-313 is a high-speed door designed for intensive use in industrial and commercial environments.', '4000 mm', '4000 mm', 'N/A', 'PVC');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (5, 'es', 'Industrial Puerta Seccional ISD01', 'industrial-sectional-door-isd01-es', '<p>A robust sectional door for industrial applications.</p>', 'Industrial Puerta Seccional ISD01 | DoorHan', 'The ISD01 is a robust and reliable sectional door for all types of industrial buildings.', '8000 mm', '7000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (5, 'zh', '工业 分段门 ISD01', 'industrial-sectional-door-isd01-zh', '<p>A robust sectional door for industrial applications.</p>', '工业 分段门 ISD01 | DoorHan', 'The ISD01 is a robust and reliable sectional door for all types of industrial buildings.', '8000 mm', '7000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (5, 'fr', 'Industrielle Porte Sectionnelle ISD01', 'industrial-sectional-door-isd01-fr', '<p>A robust sectional door for industrial applications.</p>', 'Industrielle Porte Sectionnelle ISD01 | DoorHan', 'The ISD01 is a robust and reliable sectional door for all types of industrial buildings.', '8000 mm', '7000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (5, 'ar', 'صناعي باب مقطعي ISD01', 'industrial-sectional-door-isd01-ar', '<p>A robust sectional door for industrial applications.</p>', 'صناعي باب مقطعي ISD01 | DoorHan', 'The ISD01 is a robust and reliable sectional door for all types of industrial buildings.', '8000 mm', '7000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (5, 'pt', 'Industrial Porta Seccional ISD01', 'industrial-sectional-door-isd01-pt', '<p>A robust sectional door for industrial applications.</p>', 'Industrial Porta Seccional ISD01 | DoorHan', 'The ISD01 is a robust and reliable sectional door for all types of industrial buildings.', '8000 mm', '7000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (5, 'de', 'Industrie Sektionaltor ISD01', 'industrial-sectional-door-isd01-de', '<p>A robust sectional door for industrial applications.</p>', 'Industrie Sektionaltor ISD01 | DoorHan', 'The ISD01 is a robust and reliable sectional door for all types of industrial buildings.', '8000 mm', '7000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (5, 'hi', 'औद्योगिक अनुभागीय दरवाजा ISD01', 'industrial-sectional-door-isd01-hi', '<p>A robust sectional door for industrial applications.</p>', 'औद्योगिक अनुभागीय दरवाजा ISD01 | DoorHan', 'The ISD01 is a robust and reliable sectional door for all types of industrial buildings.', '8000 mm', '7000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (5, 'id', 'Industri Pintu Sectional ISD01', 'industrial-sectional-door-isd01-id', '<p>A robust sectional door for industrial applications.</p>', 'Industri Pintu Sectional ISD01 | DoorHan', 'The ISD01 is a robust and reliable sectional door for all types of industrial buildings.', '8000 mm', '7000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (5, 'ja', '産業用 セクショナルドア ISD01', 'industrial-sectional-door-isd01-ja', '<p>A robust sectional door for industrial applications.</p>', '産業用 セクショナルドア ISD01 | DoorHan', 'The ISD01 is a robust and reliable sectional door for all types of industrial buildings.', '8000 mm', '7000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (5, 'ko', '산업용 섹션 도어 ISD01', 'industrial-sectional-door-isd01-ko', '<p>A robust sectional door for industrial applications.</p>', '산업용 섹션 도어 ISD01 | DoorHan', 'The ISD01 is a robust and reliable sectional door for all types of industrial buildings.', '8000 mm', '7000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (5, 'it', 'Industriale Porta Sezionale ISD01', 'industrial-sectional-door-isd01-it', '<p>A robust sectional door for industrial applications.</p>', 'Industriale Porta Sezionale ISD01 | DoorHan', 'The ISD01 is a robust and reliable sectional door for all types of industrial buildings.', '8000 mm', '7000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (6, 'es', 'Yett 01', 'yett-01-es', '<p>Yett 01 is a great choice for residential garages.</p>', 'Yett 01 | DoorHan', 'Yett 01 offers the perfect balance of modern design, security, and affordability for your home.', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (6, 'zh', 'Yett 01', 'yett-01-zh', '<p>Yett 01 is a great choice for residential garages.</p>', 'Yett 01 | DoorHan', 'Yett 01 offers the perfect balance of modern design, security, and affordability for your home.', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (6, 'fr', 'Yett 01', 'yett-01-fr', '<p>Yett 01 is a great choice for residential garages.</p>', 'Yett 01 | DoorHan', 'Yett 01 offers the perfect balance of modern design, security, and affordability for your home.', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (6, 'ar', 'Yett 01', 'yett-01-ar', '<p>Yett 01 is a great choice for residential garages.</p>', 'Yett 01 | DoorHan', 'Yett 01 offers the perfect balance of modern design, security, and affordability for your home.', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (6, 'pt', 'Yett 01', 'yett-01-pt', '<p>Yett 01 is a great choice for residential garages.</p>', 'Yett 01 | DoorHan', 'Yett 01 offers the perfect balance of modern design, security, and affordability for your home.', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (6, 'de', 'Yett 01', 'yett-01-de', '<p>Yett 01 is a great choice for residential garages.</p>', 'Yett 01 | DoorHan', 'Yett 01 offers the perfect balance of modern design, security, and affordability for your home.', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (6, 'hi', 'Yett 01', 'yett-01-hi', '<p>Yett 01 is a great choice for residential garages.</p>', 'Yett 01 | DoorHan', 'Yett 01 offers the perfect balance of modern design, security, and affordability for your home.', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (6, 'id', 'Yett 01', 'yett-01-id', '<p>Yett 01 is a great choice for residential garages.</p>', 'Yett 01 | DoorHan', 'Yett 01 offers the perfect balance of modern design, security, and affordability for your home.', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (6, 'ja', 'Yett 01', 'yett-01-ja', '<p>Yett 01 is a great choice for residential garages.</p>', 'Yett 01 | DoorHan', 'Yett 01 offers the perfect balance of modern design, security, and affordability for your home.', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (6, 'ko', 'Yett 01', 'yett-01-ko', '<p>Yett 01 is a great choice for residential garages.</p>', 'Yett 01 | DoorHan', 'Yett 01 offers the perfect balance of modern design, security, and affordability for your home.', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (6, 'it', 'Yett 01', 'yett-01-it', '<p>Yett 01 is a great choice for residential garages.</p>', 'Yett 01 | DoorHan', 'Yett 01 offers the perfect balance of modern design, security, and affordability for your home.', '3000 mm', '2700 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (7, 'es', 'Yett 02', 'yett-02-es', '<p>Yett 02 provides superior insulation and a premium finish.</p>', 'Yett 02 | DoorHan', 'Keep your garage warm and secure with the Yett 02, featuring superior insulation properties.', '5500 mm', '3000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (7, 'zh', 'Yett 02', 'yett-02-zh', '<p>Yett 02 provides superior insulation and a premium finish.</p>', 'Yett 02 | DoorHan', 'Keep your garage warm and secure with the Yett 02, featuring superior insulation properties.', '5500 mm', '3000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (7, 'fr', 'Yett 02', 'yett-02-fr', '<p>Yett 02 provides superior insulation and a premium finish.</p>', 'Yett 02 | DoorHan', 'Keep your garage warm and secure with the Yett 02, featuring superior insulation properties.', '5500 mm', '3000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (7, 'ar', 'Yett 02', 'yett-02-ar', '<p>Yett 02 provides superior insulation and a premium finish.</p>', 'Yett 02 | DoorHan', 'Keep your garage warm and secure with the Yett 02, featuring superior insulation properties.', '5500 mm', '3000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (7, 'pt', 'Yett 02', 'yett-02-pt', '<p>Yett 02 provides superior insulation and a premium finish.</p>', 'Yett 02 | DoorHan', 'Keep your garage warm and secure with the Yett 02, featuring superior insulation properties.', '5500 mm', '3000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (7, 'de', 'Yett 02', 'yett-02-de', '<p>Yett 02 provides superior insulation and a premium finish.</p>', 'Yett 02 | DoorHan', 'Keep your garage warm and secure with the Yett 02, featuring superior insulation properties.', '5500 mm', '3000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (7, 'hi', 'Yett 02', 'yett-02-hi', '<p>Yett 02 provides superior insulation and a premium finish.</p>', 'Yett 02 | DoorHan', 'Keep your garage warm and secure with the Yett 02, featuring superior insulation properties.', '5500 mm', '3000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (7, 'id', 'Yett 02', 'yett-02-id', '<p>Yett 02 provides superior insulation and a premium finish.</p>', 'Yett 02 | DoorHan', 'Keep your garage warm and secure with the Yett 02, featuring superior insulation properties.', '5500 mm', '3000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (7, 'ja', 'Yett 02', 'yett-02-ja', '<p>Yett 02 provides superior insulation and a premium finish.</p>', 'Yett 02 | DoorHan', 'Keep your garage warm and secure with the Yett 02, featuring superior insulation properties.', '5500 mm', '3000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (7, 'ko', 'Yett 02', 'yett-02-ko', '<p>Yett 02 provides superior insulation and a premium finish.</p>', 'Yett 02 | DoorHan', 'Keep your garage warm and secure with the Yett 02, featuring superior insulation properties.', '5500 mm', '3000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (7, 'it', 'Yett 02', 'yett-02-it', '<p>Yett 02 provides superior insulation and a premium finish.</p>', 'Yett 02 | DoorHan', 'Keep your garage warm and secure with the Yett 02, featuring superior insulation properties.', '5500 mm', '3000 mm', '40 mm', 'Polyurethane');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (8, 'es', 'Portón Plegable', 'folding-gate-es', '<p>Industrial folding gate for hangars and depots.</p>', 'Portón Plegable | DoorHan', 'Our industrial folding gates are the perfect solution for extra-large openings like aircraft hangars.', '30000 mm', '8000 mm', 'N/A', 'Mineral Wool');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (8, 'zh', '折叠门', 'folding-gate-zh', '<p>工业 folding gate for hangars and depots.</p>', '折叠门 | DoorHan', 'Our industrial folding gates are the perfect solution for extra-large openings like aircraft hangars.', '30000 mm', '8000 mm', 'N/A', 'Mineral Wool');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (8, 'fr', 'Portail Pliant', 'folding-gate-fr', '<p>Industrielle folding gate for hangars and depots.</p>', 'Portail Pliant | DoorHan', 'Our industrial folding gates are the perfect solution for extra-large openings like aircraft hangars.', '30000 mm', '8000 mm', 'N/A', 'Mineral Wool');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (8, 'ar', 'بوابة قابلة للطي', 'folding-gate-ar', '<p>صناعي folding gate for hangars and depots.</p>', 'بوابة قابلة للطي | DoorHan', 'Our industrial folding gates are the perfect solution for extra-large openings like aircraft hangars.', '30000 mm', '8000 mm', 'N/A', 'Mineral Wool');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (8, 'pt', 'Portão Dobrável', 'folding-gate-pt', '<p>Industrial folding gate for hangars and depots.</p>', 'Portão Dobrável | DoorHan', 'Our industrial folding gates are the perfect solution for extra-large openings like aircraft hangars.', '30000 mm', '8000 mm', 'N/A', 'Mineral Wool');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (8, 'de', 'Falttor', 'folding-gate-de', '<p>Industrie folding gate for hangars and depots.</p>', 'Falttor | DoorHan', 'Our industrial folding gates are the perfect solution for extra-large openings like aircraft hangars.', '30000 mm', '8000 mm', 'N/A', 'Mineral Wool');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (8, 'hi', 'फोल्डिंग गेट', 'folding-gate-hi', '<p>औद्योगिक folding gate for hangars and depots.</p>', 'फोल्डिंग गेट | DoorHan', 'Our industrial folding gates are the perfect solution for extra-large openings like aircraft hangars.', '30000 mm', '8000 mm', 'N/A', 'Mineral Wool');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (8, 'id', 'Gerbang Lipat', 'folding-gate-id', '<p>Industri folding gate for hangars and depots.</p>', 'Gerbang Lipat | DoorHan', 'Our industrial folding gates are the perfect solution for extra-large openings like aircraft hangars.', '30000 mm', '8000 mm', 'N/A', 'Mineral Wool');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (8, 'ja', '折りたたみゲート', 'folding-gate-ja', '<p>産業用 folding gate for hangars and depots.</p>', '折りたたみゲート | DoorHan', 'Our industrial folding gates are the perfect solution for extra-large openings like aircraft hangars.', '30000 mm', '8000 mm', 'N/A', 'Mineral Wool');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (8, 'ko', '폴딩 게이트', 'folding-gate-ko', '<p>산업용 folding gate for hangars and depots.</p>', '폴딩 게이트 | DoorHan', 'Our industrial folding gates are the perfect solution for extra-large openings like aircraft hangars.', '30000 mm', '8000 mm', 'N/A', 'Mineral Wool');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (8, 'it', 'Cancello Pieghevole', 'folding-gate-it', '<p>Industriale folding gate for hangars and depots.</p>', 'Cancello Pieghevole | DoorHan', 'Our industrial folding gates are the perfect solution for extra-large openings like aircraft hangars.', '30000 mm', '8000 mm', 'N/A', 'Mineral Wool');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (9, 'es', 'Portón Corredero DIY', 'sliding-gate-diy-es', '<p>A complete DIY kit for a self-supporting sliding gate.</p>', 'Portón Corredero DIY | DoorHan', 'Get our complete DIY kit to easily install a modern and reliable sliding gate on your property.', '4500 mm', '2200 mm', 'N/A', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (9, 'zh', '滑动门 DIY', 'sliding-gate-diy-zh', '<p>A complete DIY kit for a self-supporting sliding gate.</p>', '滑动门 DIY | DoorHan', 'Get our complete DIY kit to easily install a modern and reliable sliding gate on your property.', '4500 mm', '2200 mm', 'N/A', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (9, 'fr', 'Portail Coulissant DIY', 'sliding-gate-diy-fr', '<p>A complete DIY kit for a self-supporting sliding gate.</p>', 'Portail Coulissant DIY | DoorHan', 'Get our complete DIY kit to easily install a modern and reliable sliding gate on your property.', '4500 mm', '2200 mm', 'N/A', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (9, 'ar', 'بوابة منزلقة DIY', 'sliding-gate-diy-ar', '<p>A complete DIY kit for a self-supporting sliding gate.</p>', 'بوابة منزلقة DIY | DoorHan', 'Get our complete DIY kit to easily install a modern and reliable sliding gate on your property.', '4500 mm', '2200 mm', 'N/A', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (9, 'pt', 'Portão Deslizante DIY', 'sliding-gate-diy-pt', '<p>A complete DIY kit for a self-supporting sliding gate.</p>', 'Portão Deslizante DIY | DoorHan', 'Get our complete DIY kit to easily install a modern and reliable sliding gate on your property.', '4500 mm', '2200 mm', 'N/A', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (9, 'de', 'Schiebetor DIY', 'sliding-gate-diy-de', '<p>A complete DIY kit for a self-supporting sliding gate.</p>', 'Schiebetor DIY | DoorHan', 'Get our complete DIY kit to easily install a modern and reliable sliding gate on your property.', '4500 mm', '2200 mm', 'N/A', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (9, 'hi', 'स्लाइडिंग गेट DIY', 'sliding-gate-diy-hi', '<p>A complete DIY kit for a self-supporting sliding gate.</p>', 'स्लाइडिंग गेट DIY | DoorHan', 'Get our complete DIY kit to easily install a modern and reliable sliding gate on your property.', '4500 mm', '2200 mm', 'N/A', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (9, 'id', 'Gerbang Geser DIY', 'sliding-gate-diy-id', '<p>A complete DIY kit for a self-supporting sliding gate.</p>', 'Gerbang Geser DIY | DoorHan', 'Get our complete DIY kit to easily install a modern and reliable sliding gate on your property.', '4500 mm', '2200 mm', 'N/A', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (9, 'ja', 'スライディングゲート DIY', 'sliding-gate-diy-ja', '<p>A complete DIY kit for a self-supporting sliding gate.</p>', 'スライディングゲート DIY | DoorHan', 'Get our complete DIY kit to easily install a modern and reliable sliding gate on your property.', '4500 mm', '2200 mm', 'N/A', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (9, 'ko', '슬라이딩 게이트 DIY', 'sliding-gate-diy-ko', '<p>A complete DIY kit for a self-supporting sliding gate.</p>', '슬라이딩 게이트 DIY | DoorHan', 'Get our complete DIY kit to easily install a modern and reliable sliding gate on your property.', '4500 mm', '2200 mm', 'N/A', 'None');
INSERT INTO `product_translations` (`product_id`, `language_code`, `name`, `slug`, `content`, `seo_title`, `meta_description`, `max_width`, `max_height`, `panel_thickness`, `insulation`) VALUES (9, 'it', 'Cancello Scorrevole DIY', 'sliding-gate-diy-it', '<p>A complete DIY kit for a self-supporting sliding gate.</p>', 'Cancello Scorrevole DIY | DoorHan', 'Get our complete DIY kit to easily install a modern and reliable sliding gate on your property.', '4500 mm', '2200 mm', 'N/A', 'None');

-- Category Translations
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (1, 'es', 'Puerta Seccionals', 'sectional-doors-es', 'Modern and efficient sectional garage doors.', 'Puerta Seccionals | DoorHan', 'Modern and efficient sectional garage doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (1, 'zh', '分段门s', 'sectional-doors-zh', 'Modern and efficient sectional garage doors.', '分段门s | DoorHan', 'Modern and efficient sectional garage doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (1, 'fr', 'Porte Sectionnelles', 'sectional-doors-fr', 'Modern and efficient sectional garage doors.', 'Porte Sectionnelles | DoorHan', 'Modern and efficient sectional garage doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (1, 'ar', 'باب مقطعيs', 'sectional-doors-ar', 'Modern and efficient sectional garage doors.', 'باب مقطعيs | DoorHan', 'Modern and efficient sectional garage doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (1, 'pt', 'Porta Seccionals', 'sectional-doors-pt', 'Modern and efficient sectional garage doors.', 'Porta Seccionals | DoorHan', 'Modern and efficient sectional garage doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (1, 'de', 'Sektionaltors', 'sectional-doors-de', 'Modern and efficient sectional garage doors.', 'Sektionaltors | DoorHan', 'Modern and efficient sectional garage doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (1, 'hi', 'अनुभागीय दरवाजाs', 'sectional-doors-hi', 'Modern and efficient sectional garage doors.', 'अनुभागीय दरवाजाs | DoorHan', 'Modern and efficient sectional garage doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (1, 'id', 'Pintu Sectionals', 'sectional-doors-id', 'Modern and efficient sectional garage doors.', 'Pintu Sectionals | DoorHan', 'Modern and efficient sectional garage doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (1, 'ja', 'セクショナルドアs', 'sectional-doors-ja', 'Modern and efficient sectional garage doors.', 'セクショナルドアs | DoorHan', 'Modern and efficient sectional garage doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (1, 'ko', '섹션 도어s', 'sectional-doors-ko', 'Modern and efficient sectional garage doors.', '섹션 도어s | DoorHan', 'Modern and efficient sectional garage doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (1, 'it', 'Porta Sezionales', 'sectional-doors-it', 'Modern and efficient sectional garage doors.', 'Porta Sezionales | DoorHan', 'Modern and efficient sectional garage doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (2, 'es', 'Persiana Enrollable Puertas', 'roller-shutter-doors-es', 'Space-saving and durable roller shutter doors.', 'Persiana Enrollable Puertas | DoorHan', 'Space-saving and durable roller shutter doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (2, 'zh', '卷帘门 门s', 'roller-shutter-doors-zh', 'Space-saving and durable roller shutter doors.', '卷帘门 门s | DoorHan', 'Space-saving and durable roller shutter doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (2, 'fr', 'Volet Roulant Portes', 'roller-shutter-doors-fr', 'Space-saving and durable roller shutter doors.', 'Volet Roulant Portes | DoorHan', 'Space-saving and durable roller shutter doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (2, 'ar', 'مصراع دوار بابs', 'roller-shutter-doors-ar', 'Space-saving and durable roller shutter doors.', 'مصراع دوار بابs | DoorHan', 'Space-saving and durable roller shutter doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (2, 'pt', 'Persiana de Enrolar Portas', 'roller-shutter-doors-pt', 'Space-saving and durable roller shutter doors.', 'Persiana de Enrolar Portas | DoorHan', 'Space-saving and durable roller shutter doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (2, 'de', 'Rollladen Tors', 'roller-shutter-doors-de', 'Space-saving and durable roller shutter doors.', 'Rollladen Tors | DoorHan', 'Space-saving and durable roller shutter doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (2, 'hi', 'रोलर शटर दरवाजाs', 'roller-shutter-doors-hi', 'Space-saving and durable roller shutter doors.', 'रोलर शटर दरवाजाs | DoorHan', 'Space-saving and durable roller shutter doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (2, 'id', 'Roller Shutter Pintus', 'roller-shutter-doors-id', 'Space-saving and durable roller shutter doors.', 'Roller Shutter Pintus | DoorHan', 'Space-saving and durable roller shutter doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (2, 'ja', 'ローラーシャッター ドアs', 'roller-shutter-doors-ja', 'Space-saving and durable roller shutter doors.', 'ローラーシャッター ドアs | DoorHan', 'Space-saving and durable roller shutter doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (2, 'ko', '롤러 셔터 도어s', 'roller-shutter-doors-ko', 'Space-saving and durable roller shutter doors.', '롤러 셔터 도어s | DoorHan', 'Space-saving and durable roller shutter doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (2, 'it', 'Serranda Avvolgibile Portas', 'roller-shutter-doors-it', 'Space-saving and durable roller shutter doors.', 'Serranda Avvolgibile Portas | DoorHan', 'Space-saving and durable roller shutter doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (3, 'es', 'Puerta Rápidas', 'high-speed-doors-es', 'Fast and reliable high-speed industrial doors.', 'Puerta Rápidas | DoorHan', 'Optimize your workflow with our fast and reliable high-speed industrial doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (3, 'zh', '快速门s', 'high-speed-doors-zh', 'Fast and reliable high-speed industrial doors.', '快速门s | DoorHan', 'Optimize your workflow with our fast and reliable high-speed industrial doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (3, 'fr', 'Porte Rapides', 'high-speed-doors-fr', 'Fast and reliable high-speed industrial doors.', 'Porte Rapides | DoorHan', 'Optimize your workflow with our fast and reliable high-speed industrial doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (3, 'ar', 'باب عالي السرعةs', 'high-speed-doors-ar', 'Fast and reliable high-speed industrial doors.', 'باب عالي السرعةs | DoorHan', 'Optimize your workflow with our fast and reliable high-speed industrial doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (3, 'pt', 'Porta Rápidas', 'high-speed-doors-pt', 'Fast and reliable high-speed industrial doors.', 'Porta Rápidas | DoorHan', 'Optimize your workflow with our fast and reliable high-speed industrial doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (3, 'de', 'Schnelllauftors', 'high-speed-doors-de', 'Fast and reliable high-speed industrial doors.', 'Schnelllauftors | DoorHan', 'Optimize your workflow with our fast and reliable high-speed industrial doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (3, 'hi', 'हाई स्पीड डोरs', 'high-speed-doors-hi', 'Fast and reliable high-speed industrial doors.', 'हाई स्पीड डोरs | DoorHan', 'Optimize your workflow with our fast and reliable high-speed industrial doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (3, 'id', 'Pintu Kecepatan Tinggis', 'high-speed-doors-id', 'Fast and reliable high-speed industrial doors.', 'Pintu Kecepatan Tinggis | DoorHan', 'Optimize your workflow with our fast and reliable high-speed industrial doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (3, 'ja', '高速ドアs', 'high-speed-doors-ja', 'Fast and reliable high-speed industrial doors.', '高速ドアs | DoorHan', 'Optimize your workflow with our fast and reliable high-speed industrial doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (3, 'ko', '고속 도어s', 'high-speed-doors-ko', 'Fast and reliable high-speed industrial doors.', '고속 도어s | DoorHan', 'Optimize your workflow with our fast and reliable high-speed industrial doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (3, 'it', 'Porta Rapidas', 'high-speed-doors-it', 'Fast and reliable high-speed industrial doors.', 'Porta Rapidas | DoorHan', 'Optimize your workflow with our fast and reliable high-speed industrial doors.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (4, 'es', 'Folding Puertas', 'folding-doors-es', 'Versatile and robust folding doors.', 'Folding Puertas | DoorHan', 'Versatile and robust folding doors for large openings.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (4, 'zh', 'Folding 门s', 'folding-doors-zh', 'Versatile and robust folding doors.', 'Folding 门s | DoorHan', 'Versatile and robust folding doors for large openings.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (4, 'fr', 'Folding Portes', 'folding-doors-fr', 'Versatile and robust folding doors.', 'Folding Portes | DoorHan', 'Versatile and robust folding doors for large openings.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (4, 'ar', 'Folding بابs', 'folding-doors-ar', 'Versatile and robust folding doors.', 'Folding بابs | DoorHan', 'Versatile and robust folding doors for large openings.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (4, 'pt', 'Folding Portas', 'folding-doors-pt', 'Versatile and robust folding doors.', 'Folding Portas | DoorHan', 'Versatile and robust folding doors for large openings.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (4, 'de', 'Folding Tors', 'folding-doors-de', 'Versatile and robust folding doors.', 'Folding Tors | DoorHan', 'Versatile and robust folding doors for large openings.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (4, 'hi', 'Folding दरवाजाs', 'folding-doors-hi', 'Versatile and robust folding doors.', 'Folding दरवाजाs | DoorHan', 'Versatile and robust folding doors for large openings.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (4, 'id', 'Folding Pintus', 'folding-doors-id', 'Versatile and robust folding doors.', 'Folding Pintus | DoorHan', 'Versatile and robust folding doors for large openings.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (4, 'ja', 'Folding ドアs', 'folding-doors-ja', 'Versatile and robust folding doors.', 'Folding ドアs | DoorHan', 'Versatile and robust folding doors for large openings.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (4, 'ko', 'Folding 도어s', 'folding-doors-ko', 'Versatile and robust folding doors.', 'Folding 도어s | DoorHan', 'Versatile and robust folding doors for large openings.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (4, 'it', 'Folding Portas', 'folding-doors-it', 'Versatile and robust folding doors.', 'Folding Portas | DoorHan', 'Versatile and robust folding doors for large openings.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (5, 'es', 'Portón Correderos', 'sliding-gates-es', 'Automatic sliding gates for secure access.', 'Portón Correderos | DoorHan', 'Automatic sliding gates for secure and convenient access.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (5, 'zh', '滑动门s', 'sliding-gates-zh', 'Automatic sliding gates for secure access.', '滑动门s | DoorHan', 'Automatic sliding gates for secure and convenient access.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (5, 'fr', 'Portail Coulissants', 'sliding-gates-fr', 'Automatic sliding gates for secure access.', 'Portail Coulissants | DoorHan', 'Automatic sliding gates for secure and convenient access.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (5, 'ar', 'بوابة منزلقةs', 'sliding-gates-ar', 'Automatic sliding gates for secure access.', 'بوابة منزلقةs | DoorHan', 'Automatic sliding gates for secure and convenient access.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (5, 'pt', 'Portão Deslizantes', 'sliding-gates-pt', 'Automatic sliding gates for secure access.', 'Portão Deslizantes | DoorHan', 'Automatic sliding gates for secure and convenient access.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (5, 'de', 'Schiebetors', 'sliding-gates-de', 'Automatic sliding gates for secure access.', 'Schiebetors | DoorHan', 'Automatic sliding gates for secure and convenient access.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (5, 'hi', 'स्लाइडिंग गेटs', 'sliding-gates-hi', 'Automatic sliding gates for secure access.', 'स्लाइडिंग गेटs | DoorHan', 'Automatic sliding gates for secure and convenient access.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (5, 'id', 'Gerbang Gesers', 'sliding-gates-id', 'Automatic sliding gates for secure access.', 'Gerbang Gesers | DoorHan', 'Automatic sliding gates for secure and convenient access.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (5, 'ja', 'スライディングゲートs', 'sliding-gates-ja', 'Automatic sliding gates for secure access.', 'スライディングゲートs | DoorHan', 'Automatic sliding gates for secure and convenient access.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (5, 'ko', '슬라이딩 게이트s', 'sliding-gates-ko', 'Automatic sliding gates for secure access.', '슬라이딩 게이트s | DoorHan', 'Automatic sliding gates for secure and convenient access.');
INSERT INTO `category_translations` (`category_id`, `language_code`, `name`, `slug`, `description`, `seo_title`, `meta_description`) VALUES (5, 'it', 'Cancello Scorrevoles', 'sliding-gates-it', 'Automatic sliding gates for secure access.', 'Cancello Scorrevoles | DoorHan', 'Automatic sliding gates for secure and convenient access.');

-- Post Translations
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (1, 'es', 'Nueva Línea de Productos', 'new-product-line-es', '<p>We are excited to announce our new product line.</p>', 'Nueva Línea de Productos', 'We are excited to announce our new product line.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (1, 'zh', '新产品线', 'new-product-line-zh', '<p>We are excited to announce our new product line.</p>', '新产品线', 'We are excited to announce our new product line.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (1, 'fr', 'Nouvelle Gamme de Produits', 'new-product-line-fr', '<p>We are excited to announce our new product line.</p>', 'Nouvelle Gamme de Produits', 'We are excited to announce our new product line.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (1, 'ar', 'خط إنتاج جديد', 'new-product-line-ar', '<p>We are excited to announce our new product line.</p>', 'خط إنتاج جديد', 'We are excited to announce our new product line.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (1, 'pt', 'Nova Linha de Produtos', 'new-product-line-pt', '<p>We are excited to announce our new product line.</p>', 'Nova Linha de Produtos', 'We are excited to announce our new product line.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (1, 'de', 'Neue Produktlinie', 'new-product-line-de', '<p>We are excited to announce our new product line.</p>', 'Neue Produktlinie', 'We are excited to announce our new product line.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (1, 'hi', 'नई उत्पाद लाइन', 'new-product-line-hi', '<p>We are excited to announce our new product line.</p>', 'नई उत्पाद लाइन', 'We are excited to announce our new product line.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (1, 'id', 'Lini Produk Baru', 'new-product-line-id', '<p>We are excited to announce our new product line.</p>', 'Lini Produk Baru', 'We are excited to announce our new product line.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (1, 'ja', '新製品ライン', 'new-product-line-ja', '<p>We are excited to announce our new product line.</p>', '新製品ライン', 'We are excited to announce our new product line.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (1, 'ko', '신제품 라인', 'new-product-line-ko', '<p>We are excited to announce our new product line.</p>', '신제품 라인', 'We are excited to announce our new product line.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (1, 'it', 'Nuova Linea Prodotti', 'new-product-line-it', '<p>We are excited to announce our new product line.</p>', 'Nuova Linea Prodotti', 'We are excited to announce our new product line.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (2, 'es', 'PuertaHan at Exposición', 'doorhan-at-exhibition-es', '<p>PuertaHan will be participating in the upcoming construction exhibition.</p>', 'PuertaHan at Exposición', 'PuertaHan will be participating in the upcoming construction exhibition.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (2, 'zh', '门Han at 展览', 'doorhan-at-exhibition-zh', '<p>门Han will be participating in the upcoming construction exhibition.</p>', '门Han at 展览', '门Han will be participating in the upcoming construction exhibition.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (2, 'fr', 'PorteHan at Exposition', 'doorhan-at-exhibition-fr', '<p>PorteHan will be participating in the upcoming construction exhibition.</p>', 'PorteHan at Exposition', 'PorteHan will be participating in the upcoming construction exhibition.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (2, 'ar', 'بابHan at معرض', 'doorhan-at-exhibition-ar', '<p>بابHan will be participating in the upcoming construction exhibition.</p>', 'بابHan at معرض', 'بابHan will be participating in the upcoming construction exhibition.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (2, 'pt', 'PortaHan at Exposição', 'doorhan-at-exhibition-pt', '<p>PortaHan will be participating in the upcoming construction exhibition.</p>', 'PortaHan at Exposição', 'PortaHan will be participating in the upcoming construction exhibition.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (2, 'de', 'TorHan at Ausstellung', 'doorhan-at-exhibition-de', '<p>TorHan will be participating in the upcoming construction exhibition.</p>', 'TorHan at Ausstellung', 'TorHan will be participating in the upcoming construction exhibition.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (2, 'hi', 'दरवाजाHan at प्रदर्शनी', 'doorhan-at-exhibition-hi', '<p>दरवाजाHan will be participating in the upcoming construction exhibition.</p>', 'दरवाजाHan at प्रदर्शनी', 'दरवाजाHan will be participating in the upcoming construction exhibition.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (2, 'id', 'PintuHan at Pameran', 'doorhan-at-exhibition-id', '<p>PintuHan will be participating in the upcoming construction exhibition.</p>', 'PintuHan at Pameran', 'PintuHan will be participating in the upcoming construction exhibition.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (2, 'ja', 'ドアHan at 展示会', 'doorhan-at-exhibition-ja', '<p>ドアHan will be participating in the upcoming construction exhibition.</p>', 'ドアHan at 展示会', 'ドアHan will be participating in the upcoming construction exhibition.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (2, 'ko', '도어Han at 전시회', 'doorhan-at-exhibition-ko', '<p>도어Han will be participating in the upcoming construction exhibition.</p>', '도어Han at 전시회', '도어Han will be participating in the upcoming construction exhibition.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (2, 'it', 'PortaHan at Fiera', 'doorhan-at-exhibition-it', '<p>PortaHan will be participating in the upcoming construction exhibition.</p>', 'PortaHan at Fiera', 'PortaHan will be participating in the upcoming construction exhibition.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (3, 'es', 'Consejos de Mantenimiento', 'maintenance-tips-es', '<p>Here are some tips for maintaining your garage door.</p>', 'Consejos de Mantenimiento', 'Here are some tips for maintaining your garage door.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (3, 'zh', '维护技巧', 'maintenance-tips-zh', '<p>Here are some tips for maintaining your garage door.</p>', '维护技巧', 'Here are some tips for maintaining your garage door.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (3, 'fr', 'Conseils d''Entretien', 'maintenance-tips-fr', '<p>Here are some tips for maintaining your garage door.</p>', 'Conseils d''Entretien', 'Here are some tips for maintaining your garage door.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (3, 'ar', 'نصائح الصيانة', 'maintenance-tips-ar', '<p>Here are some tips for maintaining your garage door.</p>', 'نصائح الصيانة', 'Here are some tips for maintaining your garage door.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (3, 'pt', 'Dicas de Manutenção', 'maintenance-tips-pt', '<p>Here are some tips for maintaining your garage door.</p>', 'Dicas de Manutenção', 'Here are some tips for maintaining your garage door.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (3, 'de', 'Wartungstipps', 'maintenance-tips-de', '<p>Here are some tips for maintaining your garage door.</p>', 'Wartungstipps', 'Here are some tips for maintaining your garage door.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (3, 'hi', 'रखरखाव के सुझाव', 'maintenance-tips-hi', '<p>Here are some tips for maintaining your garage door.</p>', 'रखरखाव के सुझाव', 'Here are some tips for maintaining your garage door.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (3, 'id', 'Tips Perawatan', 'maintenance-tips-id', '<p>Here are some tips for maintaining your garage door.</p>', 'Tips Perawatan', 'Here are some tips for maintaining your garage door.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (3, 'ja', 'メンテナンスのヒント', 'maintenance-tips-ja', '<p>Here are some tips for maintaining your garage door.</p>', 'メンテナンスのヒント', 'Here are some tips for maintaining your garage door.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (3, 'ko', '유지 보수 팁', 'maintenance-tips-ko', '<p>Here are some tips for maintaining your garage door.</p>', '유지 보수 팁', 'Here are some tips for maintaining your garage door.');
INSERT INTO `post_translations` (`post_id`, `language_code`, `title`, `slug`, `content`, `seo_title`, `meta_description`) VALUES (3, 'it', 'Consigli di Manutenzione', 'maintenance-tips-it', '<p>Here are some tips for maintaining your garage door.</p>', 'Consigli di Manutenzione', 'Here are some tips for maintaining your garage door.');
